[tool.flake8]
max-line-length = 160
ignore = ["E203"]

[tool.mypy]
files = "src/**/*.py"
warn_unused_configs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_redundant_casts = true
strict_equality = true

[[tool.mypy.overrides]]
# Put dependencie's name here if mypy fails to import stubs
module = [
    "scipy.*",
    "torchvision.*",
    "tqdm.*",
    "seaborn.*",
    "clip.*",
    "wandb.*",
]
ignore_missing_imports = true
